baseURL: 'https://www.james-firth.com/ttrpg-library/'
languageCode: 'en-us'
title: 'James Games Library'
theme: 'game-library'
sectionPagesMenu: 'main'
taxonomies:
  category: categories
  series: series
  genre: genres
  tag: tags
